AWSTemplateFormatVersion: 2010-09-09
Description: ---
# This is not designed to be  deployable template, it is created to display the different parameter types that can be used for future lookup.


Metadata: 
  # The Below example shows how to arrange parameters inside the CloudFormation console when deploying, typically used to group similar parameters.
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          Default: 1. General Details
        Parameters:
          - Project
          - Environment
          - Owner
      - Label:
          Default: 2. VPC Details
        Parameters:
          - VPCID
          - SubnetID-1
          - SubnetID-2
          - SubnetID-3
      - Label:
          Default: 3. CodeBuild Details
        Parameters:
          - CodeBuildEnvironment
          - CodeBuildGitHubRepository
          - CodeBuildGitHubRepositoryOwner
          - CodeBuildGitHubAuthToken
          - CodeBuildGitHubBranch
    ParameterLabels:
      PipelineName:
        Default: "Pipeline name?"
      CodeBuildEnvironment:
        Default: Should i use a different Docker Image?


Parameters: 

  # This parameter would lookup the value of an SSM Parameter inside ParameterStore
  SSMParameterExample:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Dev/APIKeyID # This is the name of the parameter you want to lookup



  # This parameter shows all the options that can be added under a parameter
  ParameterOptionsExample:
    Type: String
    Allowed Values: # This presents a list in the cfn console that only allows the options listed to be selected
      - Value1
      - Value2
      - Value3
    Default: Value1 # This selects a default value that the parameter will be filled with
    Description: This adds a description to the parameter in the cfn console
    MinLength: 1 # Specifies a minimum length the paramter must be
    MaxLength: 1 # Specifies a maximum length the paramter must be
    # The above two can be changed to 'Value' instead of 'Length' if the parameter type is number
    NoEcho: False # This will hide the parameter value in the cfn console, good for passwords, api keys etc.
